language: r
sudo: required
cache: packages
r_packages:
- dplyr
- irlba
- Matrix
- rTensor
- slam
notifications:
  slack:
    secure: K2waEwvf8kNsy85sPdSheMIk8UE3E/V7w/Mnxqmxn4o/FmP8LMA29jkIwwp6iqefnmFQvXMe7xN2c01OTxmnMS1dfgZzvqm88rFPMekzpaZvZTRpTiIU5c9RyqrKq7aIP2l9qEZ2WARVqJBvaow2TY/y3rMHfBiE0LR0lHobAKVVaCp1jUxeJkKb4lFXtPEgA/xyMrMzwTbqr9vASrTTd86RuQMGLMYaz3jEdvaxoW1gQpx6v4Ve63nF/DYqlQihEZtG2laru4OPudbM1md2Nxd19xtCj1KheMXy01G4kMZlvJJtq8DKrE+ZIO5MYC1OCkbcJiXM8jeteZzuAvtyrkgoNZ3BRKDI9DvZTkCM0mBPAZiXNH6d7zUj0j/kTqP+d2bCuZZ+vh3Q7w/h7Xic3sfDxqTAzl2/BYctbTWfsh3qAbqsBzcPSp15g83GyF1Fn5OCMMb4xM02SNUjyqU0Ywkqmo0IXBu7H35KblFZwm+ilCjWdZo7xYcD571JeX1yjjcYikw7KK3aQaj/sGLj0t9vozOJFh3v1TU6vOBtDhTuXplUHwlLK9A3czgzdqGBEW3kmwy9v8Sz29vOPlumwGtnWGseFPRkhf0woX+S1Sx6Rxd7/gP5SHpDzvMD6tsXib9xAIbHDSmd+PIzOMLNbZZcP+2Zeh6sflEoPH3VUDg=
  notifications:
     email: false
